apiVersion: v1
kind: ConfigMap

metadata:
  name: sahil-configmap
  labels:
    app: myapplication

data:
  DB_Host: mongodb
  DB_Port: "27017"
  DB_User: admin
  APP_Name: vegetable-order-app
  APP_Port: "3000"