apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    first: app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: web

  template:
    metadata:
      labels:
        app: web

    spec:
      containers:
        - name: nginx-cont
          image: nginx:latest
          ports:
            - containerPort: 80

        - name: loc
          image: sahilahmed0029/loc:v1.0.0
          ports:
            - containerPort: 5000

        - name: vegetable
          image: sahilahmed0029/vegetable:v1.0.0
          ports:
            - containerPort: 3000

---
# ClusterIP Service for nginx
apiVersion: v1
kind: Service
metadata:
  name: nginx-service

spec:
  selector:
    app: web

  ports:
    - protocol: TCP
      port: 85
      targetPort: 80

  type: ClusterIP

---
# NodePort Service for loc container
apiVersion: v1
kind: Service
metadata:
  name: loc-service

spec:
  selector:
    app: web

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007

  type: NodePort

---
# LoadBalancer Service for vegetable container
apiVersion: v1
kind: Service
metadata:
  name: vegetable-service

spec:
  selector:
    app: web

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

  type: LoadBalancer