apiVersion: v1
kind: Pod
metadata:
  name: sahil-pod
spec:
  containers:
    - name: loc
      image: sahilahmed0029/loc:v1.0.0
      ports:
        - containerPort: 5000
    
    - name: vegetable
      image: sahilahmed0029/vegetable:v1.0.0 
      ports:
        - containerPort: 3000