apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratemystore
  labels:
    first: app

spec: #Behavior of the replicaset
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec: # spec & behavior of the pod
      containers:
        - name: ratemystore-container
          image: sahilahmed0029/ratemystore:latest
          ports:
            - containerPort: 5000


  
